"""ExpeL structured output module."""

from typing import List, Dict, Any

from pydantic import BaseModel, Field

from agential.cog.reflexion.output import ReflexionReActOutput


class ExpeLOutput(BaseModel):
    """ExpeL structured output for experiences.

    Attributes:
        question (str): The question.
        key (str): The key.
        trajectory (List[ReflexionReActOutput]): The ReflexionReAct trajectory.
        reflections (List[str]): The reflections generated by the agent.
    """

    question: str = Field(..., description="The question.")
    key: str = Field(..., description="The key.")
    trajectory: List[ReflexionReActOutput] = Field(
        ..., description="The ReflexionReAct trajectory."
    )
    reflections: List[str] = Field(
        ..., description="The reflections generated by the agent."
    )
class ExpeLOutput(BaseModel):
    """ExpeL structured output for experiences.

    Attributes:
        examples (str): The examples to be included in the output.
        insights (str): Additional insights to be included in the output.
        experience (Dict[str, Any]): The current experience.
        experience_memory (List[Dict[str, Any]]): The experience memory.
        insight_memory (List[Dict[str, Any]]): The insight memory.
    """

    examples: str = Field(..., description="The examples to be included in the output.")
    insights: str = Field("", description="Additional insights to be included in the output.")
    experience: Dict[str, Any] = Field(
        ..., description="The current experience."
    )
    experience_memory: List[Dict[str, Any]] = Field(
        ..., description="The experience memory."
    )
    insight_memory: List[Dict[str, Any]] = Field(
        ..., description="The insight memory."
    )