[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agential"
version = "0.2.1"
description = "A flexible agent library."
authors = [
    {name = "Vincent Tu", email = "tuvincent0106@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
keywords = ["agent", "LLM", "uv"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
]

[project.optional-dependencies]
dev = [
    "python-dotenv>=1.0.0",
    "ruff>=0.0.289",
    "ipython>=8.15.0",
    "pytest>=7.4.2",
    "pytest-cov>=4.1.0",
    "cookiecutter>=2.5.0",
]

[project.urls]
Repository = "https://github.com/alckasoc/agential"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests that are slow to run (deselect with '-m \"not slow\"')"
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
format = "github"
select = [
    "D",  # pydocstyle
    "I",  # isort
]
target-version = "py311"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
force-wrap-aliases = true
combine-as-imports = true
lines-between-types = 1

[tool.mypy]
ignore_missing_imports = "True"
disallow_untyped_defs = "True"
allow_redefinition = "True"