# credit to https://github.com/langchain-ai/langchain/tree/master/.github/ISSUE_TEMPLATE!
name: "ðŸ› Bug Report"
description: Submit a bug report.
title: "[Bug]: "
labels: ["01 Bug Report", "bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for filling out this bug report!
  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: >
        Please describe your system information.
      placeholder: OS, python version, installation method, environment, etc.
    validations:
      required: true
  - type: checkboxes
    id: information-scripts-examples
    attributes:
      label: Information
      description: "The problem arises when using:"
      options:
        - label: "The official example notebooks/scripts"
        - label: "My own modified scripts"
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a [code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        Steps to reproduce the behavior:

          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you would expect to happen."