"""ExpeL Agent."""

from .agent import ExpeLAgent
from agential.agents.reflexion import Reflexion
from agential.agents.expel.prompts import (
    EXPEL_REFLEXION_REACT_INSTRUCTION_HOTPOTQA,
    EXPEL_REFLEXION_REACT_INSTRUCTION_FEVER,
    EXPEL_REFLEXION_REACT_INSTRUCTION_TRIVIAQA,
    EXPEL_REFLEXION_REACT_INSTRUCTION_AMBIGNQ,
    EXPEL_REFLEXION_REACT_INSTRUCTION_GSM8K,
    EXPEL_REFLEXION_REACT_INSTRUCTION_SVAMP,
    EXPEL_REFLEXION_REACT_INSTRUCTION_TABMWP,
    EXPEL_REFLEXION_REACT_INSTRUCTION_HUMANEVAL,
    EXPEL_REFLEXION_REACT_INSTRUCTION_MBPP,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_HOTPOTQA,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_FEVER,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_TRIVIAQA,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_AMBIGNQ,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_GSM8K,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_SVAMP,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_TABMWP,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_HUMANEVAL,
    EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_MBPP,
    HOTPOTQA_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    FEVER_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    TRIVIAQA_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    AMBIGNQ_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    GSM8K_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    SVAMP_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    TABMWP_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    HUMANEVAL_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    MBPP_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
    HOTPOTQA_FEWSHOT_EXAMPLES_REACT,
    FEVER_FEWSHOT_EXAMPLES_REACT,
    TRIVIAQA_FEWSHOT_EXAMPLES_REACT,
    AMBIGNQ_FEWSHOT_EXAMPLES_REACT,
    GSM8K_FEWSHOT_EXAMPLES_REACT,
    SVAMP_FEWSHOT_EXAMPLES_REACT,
    TABMWP_FEWSHOT_EXAMPLES_REACT,
    HUMANEVAL_FEWSHOT_EXAMPLES_REACT,
    MBPP_FEWSHOT_EXAMPLES_REACT,
)


EXPEL_BENCHMARK_CONFIG = {
    # QA
    "hotpotqa": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_HOTPOTQA,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_HOTPOTQA,
        "fewshot": HOTPOTQA_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": HOTPOTQA_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    "fever": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_FEVER,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_FEVER,
        "fewshot": FEVER_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": FEVER_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    "triviaqa": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_TRIVIAQA,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_TRIVIAQA,
        "fewshot": TRIVIAQA_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": TRIVIAQA_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    "ambignq": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_AMBIGNQ,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_AMBIGNQ,
        "fewshot": AMBIGNQ_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": AMBIGNQ_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    # Math
    "gsm8k": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_GSM8K,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_GSM8K,
        "fewshot": GSM8K_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": GSM8K_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    "svamp": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_SVAMP,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_SVAMP,
        "fewshot": SVAMP_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": SVAMP_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    "tabmwp": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_TABMWP,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_TABMWP,
        "fewshot": TABMWP_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": TABMWP_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    # Code
    "humaneval": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_HUMANEVAL,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_HUMANEVAL,
        "fewshot": HUMANEVAL_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": HUMANEVAL_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
    "mbpp": {
        "prompt": EXPEL_REFLEXION_REACT_INSTRUCTION_MBPP,
        "reflect_prompt": EXPEL_REFLEXION_REACT_REFLECT_INSTRUCTION_MBPP,
        "fewshot": MBPP_FEWSHOT_EXAMPLES_REACT,
        "reflect_fewshot": MBPP_FEWSHOT_EXAMPLES_EXPEL_REFLEXION_REACT_REFLECT,
        "agent": ExpeLAgent,
    },
}

class ExpeL:
    def __init__(self, llm, benchmark, *args, **kwargs):
        try:
            config = EXPEL_BENCHMARK_CONFIG[benchmark]
            agent_cls = config["agent"]
        except KeyError:
            raise ValueError(f"Unknown benchmark: {benchmark}")
        
        self._agent = agent_cls(
            llm=llm,
            benchmark=benchmark,
            config=config,
            *args,
            **kwargs
        )
        self.llm = self._agent.llm
        self.benchmark = self._agent.benchmark
        self.config = getattr(self._agent, "config", {})

    def generate(self, question: str, **kwargs):
        return self._agent.generate(question, **kwargs)

__all__ = ["ExpeL"]
