"""
Shared utilities for EXPEL agents.
"""

import random
import re
from itertools import chain
from typing import Any, Dict, List, Tuple

from agential.agents.reflexion import Reflexion
from agential.core.llm import BaseLLM, Response
from agential.agents.expel.prompts import (
    CRITIQUE_SUMMARY_SUFFIX_FULL,
    CRITIQUE_SUMMARY_SUFFIX_NOT_FULL,
    EXISTING_INSIGHTS_AI_NAME,
    HUMAN_CRITIQUE_EXISTING_INSIGHTS_ALL_SUCCESS_TEMPLATE,
    HUMAN_CRITIQUE_EXISTING_INSIGHTS_TEMPLATE,
    NON_EXISTENT_INSIGHTS_AT_NAME,
    SYSTEM_CRITIQUE_ALL_SUCCESS_EXISTING_INSIGHTS_INSTRUCTION,
    SYSTEM_CRITIQUE_EXISTING_INSIGHTS_INSTRUCTION,
    SYSTEM_TEMPLATE,
)


# ============================================================================
# EXPERIENCE GATHERING
# ============================================================================


def gather_experience(
    reflexion_react_agent: Reflexion,
    questions: List[str],
    keys: List[str],
    examples: str,
    prompt: str,
    reflect_examples: str,
    reflect_prompt: str,
    reflect_strategy: str = "reflexion",
    additional_keys: List[Dict[str, str]] = [],
    reflect_additional_keys: List[Dict[str, str]] = [],
    patience: int = 3,
) -> List[Dict[str, Any]]:
    """Collects and aggregates experiences from a ReflexionReAct by generating trajectories and reflections for a set of questions and keys.

    The function iterates over each question-key pair, generates a trajectory using the specified strategy, and records the reflections generated by the agent. Each trajectory and its corresponding reflections are appended to their respective lists within the 'experiences' dictionary.

    Parameters:
        reflexion_react_agent (ReflexionReAct): The agent from which experiences are generated.
        questions (List[str]): A list of questions to be processed by the agent.
        keys (List[str]): A list of keys that are paired with the questions to guide the agent's generation.
        examples (str, optional): Fewshot examples.
        prompt (str, optional): Prompt template string.
        reflect_examples (str, optional): Reflection fewshot examples.
        reflect_prompt (str, optional): Reflect prompt template string.
        reflect_strategy (str, optional): The strategy used to generate experiences. Defaults to "reflexion" if not specified.
        additional_keys (List[Dict[str, str]]): Additional keys for the prompt. Defaults to [].
        reflect_additional_keys (List[Dict[str, str]]): Additional keys for the reflect prompt. Defaults to [].
        patience (int, optional): The patience for the agent. Defaults to 3.

    Returns:
        List[Dict[str, Any]]: A list of dictionaries, each containing the question, key, trajectory, and reflections.
    """
    if not additional_keys:
        additional_keys = [{} for _ in range(len(questions))]

    if not reflect_additional_keys:
        reflect_additional_keys = [{} for _ in range(len(questions))]

    experiences = []
    for question, key, main_keys, reflect_keys in zip(
        questions, keys, additional_keys, reflect_additional_keys
    ):
        trajectory = reflexion_react_agent.generate(
            question=question,
            key=key,
            examples=examples,
            prompt=prompt,
            reflect_examples=reflect_examples,
            reflect_prompt=reflect_prompt,
            reflect_strategy=reflect_strategy,
            additional_keys=main_keys,  # type: ignore
            reflect_additional_keys=reflect_keys,  # type: ignore
            patience=patience,
            reset=True,
        )

        reflections = [
            trial.reflections
            for trial in trajectory.additional_info
            if trial.reflections
        ]
        selected_reflections = list(set(list(chain.from_iterable(reflections))))  # type: ignore
        experience = {
            "question": question,
            "key": key,
            "trajectory": trajectory,
            "reflections": selected_reflections,
        }
        experiences.append(experience)

    return experiences


# ============================================================================
# INSIGHT EXTRACTION
# ============================================================================


def categorize_experiences(experiences: List[Dict[str, Any]]) -> Dict[str, List]:
    """Categorizes experiences based on the success of trials in the trajectories.

    This function iterates over each index in the experiences and categorizes them into 'compare', 'success', or 'fail' based on the outcomes of the trials. Each trial is represented by a tuple, with the first element indicating success (True) or failure (False).

    Parameters:
        experiences (List[Dict[str, Any]]): A list of dictionaries, each containing the question, key, trajectory, and reflections.

    Returns:
        Dict[str, List]: A dictionary with the indices of tasks categorized into 'compare', 'success', and 'fail'.

    Raises:
    - ValueError: If a trajectory does not fit into any category, indicating an unhandled scenario.
    """
    count_dict: Dict[str, List] = {"compare": [], "success": [], "fail": []}

    for idx, experience in enumerate(experiences):
        trajectory = experience["trajectory"]
        trials_are_correct = [
            trial.steps[-1].is_correct for trial in trajectory.additional_info
        ]

        # Success.
        if (
            all(trials_are_correct) and len(trials_are_correct) == 1
        ):  # If success @ first trial, then stop generation.
            count_dict["success"].append(idx)
        # Compare.
        elif trials_are_correct[
            -1
        ]:  # If fail(s), then succeeds, then only last trial is True.
            count_dict["compare"].append(idx)
        # Fail.
        elif not all(trials_are_correct):  # All trials failed, then fail case.
            count_dict["fail"].append(idx)
        else:
            raise ValueError(f"Unhandled scenario for trajectory at index {idx}.")

    return count_dict


def get_folds(
    categories: Dict[str, List], n_instances: int, n_folds: int = 2, seed: int = 42
) -> Dict[int, List]:
    """Distributes indices into a specified number of stratified folds for cross-validation.

    Indices from each category ('compare', 'success', 'fail') are shuffled and then distributed across the folds. Each fold will serve as a validation set once during cross-validation, with the remaining data used for training.

    Parameters:
        categories (Dict[str, List]): A dictionary containing lists of indices for each category.
        n_instances (int): The total number of instances across all categories.
        n_folds (int, optional): The number of folds to create for cross-validation. Default is 2.

    Returns:
        Dict[int, List]: A dictionary where keys are fold indices and values are the lists of indices representing the training set for that fold.
    """
    random.seed(seed)

    folds: Dict[int, List] = {fold: [] for fold in range(n_folds)}

    # Assign labels for 'compare', 'success', and  'fail'.
    for _, indices in categories.items():
        indices = random.sample(indices, len(indices))
        for count, idx in enumerate(indices):
            folds[count % n_folds].append(idx)

    # Each fold is a validation set. Take the difference to get the training set of each fold.
    folds = {
        fold: list(set(list(range(n_instances))).difference(values))
        for fold, values in folds.items()
    }

    return folds


def _build_compare_prompt(
    insights: List[Dict[str, Any]],
    question: str,
    success_trial: str,
    failed_trial: str,
    is_full: bool,
) -> str:
    """Constructs a comparison prompt for an AI by combining system instructions, task details, and a list of existing insights.

    This function formats a prompt intended for AI to critique existing insights based on a given task. The task is described by a question and includes examples of both successful and failed trials.

    Parameters:
        insights (List[Tuple[str, int]]): A list of strings where each string represents an existing insight with a score. If the list is empty, it is treated as if there are no existing insights.
        question (str): The question that defines the task.
        success_trial (str): A description or example of a successful trial for the task.
        failed_trial (str): A description or example of a failed trial for the task.
        is_full (bool): A flag indicating whether the prompt should be in its full form or not. This affects the suffix of the critique summary.

    Returns:
        str: A fully constructed prompt ready to be presented to the AI. The prompt includes a prefixed system instruction, task details formatted according to human critique template,
            and a suffix based on whether the prompt is in its full form.
    """
    if not insights:
        insights_str = NON_EXISTENT_INSIGHTS_AT_NAME
    else:
        insights_str = EXISTING_INSIGHTS_AI_NAME + "\n".join(
            [f"{i + 1}. {insight['insight']}" for i, insight in enumerate(insights)]
        )

    human_critique = HUMAN_CRITIQUE_EXISTING_INSIGHTS_TEMPLATE.format(
        question=question,
        success_trial=success_trial,
        failed_trial=failed_trial,
        insights=insights_str,
    )

    if is_full:
        suffix = CRITIQUE_SUMMARY_SUFFIX_FULL
    else:
        suffix = CRITIQUE_SUMMARY_SUFFIX_NOT_FULL

    return SYSTEM_TEMPLATE + human_critique + suffix


def _build_all_success_prompt(
    insights: List[Dict[str, Any]],
    success_trajs_str: str,
    is_full: bool,
) -> str:
    """Constructs a prompt for AI to critique existing insights based on all successful trajectories.

    This function formats a prompt intended for AI to critique existing insights when all trials are successful. The prompt includes system instructions, task details, and a list of existing insights.

    Parameters:
        insights (List[Tuple[str, int]]): A list of strings where each string represents an existing insight with a score. If the list is empty, it is treated as if there are no existing insights.
        success_trajs_str (str): A string containing all successful trajectories.
        is_full (bool): A flag indicating whether the prompt should be in its full form or not. This affects the suffix of the critique summary.

    Returns:
        str: A fully constructed prompt ready to be presented to the AI. The prompt includes a prefixed system instruction, task details formatted according to human critique template,
            and a suffix based on whether the prompt is in its full form.
    """
    if not insights:
        insights_str = NON_EXISTENT_INSIGHTS_AT_NAME
    else:
        insights_str = EXISTING_INSIGHTS_AI_NAME + "\n".join(
            [f"{i + 1}. {insight['insight']}" for i, insight in enumerate(insights)]
        )

    human_critique = HUMAN_CRITIQUE_EXISTING_INSIGHTS_ALL_SUCCESS_TEMPLATE.format(
        success_trajs=success_trajs_str,
        insights=insights_str,
    )

    if is_full:
        suffix = CRITIQUE_SUMMARY_SUFFIX_FULL
    else:
        suffix = CRITIQUE_SUMMARY_SUFFIX_NOT_FULL

    return SYSTEM_TEMPLATE + human_critique + suffix


def _prompt_compare_critique(
    llm: BaseLLM,
    insights: List[Dict[str, Any]],
    question: str,
    success_trial: str,
    failed_trial: str,
    is_full: bool,
) -> Response:
    """Generates a critique response from an LLM for comparing insights based on success and failure trials.

    This function constructs a prompt for comparing insights and sends it to the specified language model to generate a critique response.

    Parameters:
        llm (BaseLLM): The language model to generate the critique response.
        insights (List[Tuple[str, int]]): A list of existing insights to be critiqued.
        question (str): The question that defines the task.
        success_trial (str): A description or example of a successful trial for the task.
        failed_trial (str): A description or example of a failed trial for the task.
        is_full (bool): A flag indicating whether the prompt should be in its full form or not.

    Returns:
        Response: The response from the language model containing the critique.
    """
    prompt = _build_compare_prompt(
        insights=insights,
        question=question,
        success_trial=success_trial,
        failed_trial=failed_trial,
        is_full=is_full,
    )
    return llm(prompt)


def _prompt_all_success_critique(
    llm: BaseLLM,
    insights: List[Dict[str, Any]],
    success_trajs_str: str,
    is_full: bool,
) -> Response:
    """Generates a critique response from an LLM for insights based on all successful trajectories.

    This function constructs a prompt for critiquing insights when all trials are successful and sends it to the specified language model to generate a critique response.

    Parameters:
        llm (BaseLLM): The language model to generate the critique response.
        insights (List[Tuple[str, int]]): A list of existing insights to be critiqued.
        success_trajs_str (str): A string containing all successful trajectories.
        is_full (bool): A flag indicating whether the prompt should be in its full form or not.

    Returns:
        Response: The response from the language model containing the critique.
    """
    prompt = _build_all_success_prompt(
        insights=insights,
        success_trajs_str=success_trajs_str,
        is_full=is_full,
    )
    return llm(prompt)


def parse_insights(llm_text: str) -> List[Tuple[str, str]]:
    """Parses insights from LLM text output.

    This function extracts insights from the LLM's text output by looking for numbered lists and extracting the insight text and operation.

    Parameters:
        llm_text (str): The text output from the LLM containing insights.

    Returns:
        List[Tuple[str, str]]: A list of tuples, each containing the insight text and operation.
    """
    insights = []
    lines = llm_text.strip().split("\n")

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Look for numbered patterns like "1. insight text (operation)"
        match = re.match(r"(\d+)\.\s*(.+?)\s*\(([^)]+)\)", line)
        if match:
            insight_text = match.group(2).strip()
            operation = match.group(3).strip()
            insights.append((insight_text, operation))

    return insights


def retrieve_insight_index(
    insights: List[Dict[str, Any]], operation_rule_text: str
) -> int:
    """Retrieves the index of an insight based on operation rule text.

    This function searches through a list of insights to find one that matches the given operation rule text.

    Parameters:
        insights (List[Dict[str, Any]]): A list of insight dictionaries.
        operation_rule_text (str): The operation rule text to search for.

    Returns:
        int: The index of the matching insight, or -1 if not found.
    """
    for i, insight in enumerate(insights):
        if insight["operation"] == operation_rule_text:
            return i
    return -1


def remove_err_operations(
    insights: List[Dict[str, Any]], operations: List[Tuple[str, str]]
) -> List[Tuple[str, str]]:
    """Removes error operations from a list of operations.

    This function filters out operations that would result in errors when applied to the insights list.

    Parameters:
        insights (List[Dict[str, Any]]): A list of insight dictionaries.
        operations (List[Tuple[str, str]]): A list of operations to filter.

    Returns:
        List[Tuple[str, str]]: A filtered list of operations with error-causing operations removed.
    """
    valid_operations = []
    for insight_text, operation in operations:
        if operation == "add":
            valid_operations.append((insight_text, operation))
        elif operation == "delete":
            idx = retrieve_insight_index(insights, insight_text)
            if idx != -1:
                valid_operations.append((insight_text, operation))
        elif operation == "modify":
            idx = retrieve_insight_index(insights, insight_text)
            if idx != -1:
                valid_operations.append((insight_text, operation))
        else:
            # Skip unknown operations
            continue

    return valid_operations


def accumulate_metrics(
    compares_response: List[List[Response]],
    successes_response: List[List[Response]],
    experiences: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Accumulates metrics from compare and success responses.

    This function calculates various metrics from the responses and experiences, including total tokens, costs, and times.

    Parameters:
        compares_response (List[List[Response]]): A list of compare response lists.
        successes_response (List[List[Response]]): A list of success response lists.
        experiences (List[Dict[str, Any]]): A list of experience dictionaries.

    Returns:
        Dict[str, Any]: A dictionary containing accumulated metrics.
    """
    total_prompt_tokens = 0
    total_completion_tokens = 0
    total_prompt_cost = 0.0
    total_completion_cost = 0.0
    total_prompt_time = 0.0

    # Accumulate from compare responses
    for response_list in compares_response:
        for response in response_list:
            total_prompt_tokens += getattr(response, "prompt_tokens", 0)
            total_completion_tokens += getattr(response, "completion_tokens", 0)
            total_prompt_cost += getattr(response, "prompt_cost", 0.0)
            total_completion_cost += getattr(response, "completion_cost", 0.0)
            total_prompt_time += getattr(response, "prompt_time", 0.0)

    # Accumulate from success responses
    for response_list in successes_response:
        for response in response_list:
            total_prompt_tokens += getattr(response, "prompt_tokens", 0)
            total_completion_tokens += getattr(response, "completion_tokens", 0)
            total_prompt_cost += getattr(response, "prompt_cost", 0.0)
            total_completion_cost += getattr(response, "completion_cost", 0.0)
            total_prompt_time += getattr(response, "prompt_time", 0.0)

    # Accumulate from experiences
    for experience in experiences:
        trajectory = experience["trajectory"]
        total_prompt_tokens += getattr(trajectory, "total_prompt_tokens", 0)
        total_completion_tokens += getattr(trajectory, "total_completion_tokens", 0)
        total_prompt_cost += getattr(trajectory, "total_prompt_cost", 0.0)
        total_completion_cost += getattr(trajectory, "total_completion_cost", 0.0)
        total_prompt_time += getattr(trajectory, "total_prompt_time", 0.0)

    return {
        "total_prompt_tokens": total_prompt_tokens,
        "total_completion_tokens": total_completion_tokens,
        "total_tokens": total_prompt_tokens + total_completion_tokens,
        "total_prompt_cost": total_prompt_cost,
        "total_completion_cost": total_completion_cost,
        "total_cost": total_prompt_cost + total_completion_cost,
        "total_prompt_time": total_prompt_time,
    } 