wandb_version: 1

model:
  desc: null
  value: gpt-3.5-turbo
eval_model:
  desc: null
  value: gpt-4o-mini
seed:
  desc: null
  value: 42
num_retries:
  desc: null
  value: 1
warming:
  desc: null
  value:
  - 0.0
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1727823697
    t:
      1:
      - 49
      - 51
      - 55
      - 95
      - 105
      2:
      - 49
      - 51
      - 55
      - 95
      - 105
      3:
      - 15
      - 16
      - 23
      4: 3.11.5
      5: 0.17.9
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
