"""Base output class."""

from typing import Any
from pydantic import BaseModel, Field

class BaseOutput(BaseModel):
    """Base class for structured agent outputs.

    Attributes:
        answer (Any): The answer generated by the agent.
        additional_info (Any): A general attribute for additional information.
    """

    answer: Any = Field(..., description="The answer generated by the agent.")
    total_input_tokenss: int = Field(..., description="Total input tokens used.")
    total_output_tokens: int = Field(..., description="Total output tokens used.")
    total_tokens: int = Field(..., description="Total tokens used.")
    total_cost: float = Field(..., description="Total cost of the output.")
    total_time: float = Field(..., description="Total time taken to generate the output in seconds.")
    additional_info: Any = Field(..., description="Additional information related to the output.")
