"""LATS structured output module."""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from agential.cog.base.output import BaseOutput
from agential.utils.metrics import PromptInfo


class LATSReActStepOutput(BaseModel):
    """LATS ReAct Pydantic output class.

    Attributes:
        thought (str): The thought process of the agent.
        action_type (str): The type of action performed by the agent.
        query (str): The query requested by the agent.
        observation (str): The observation made by the agent.
        answer (str): The answer generated by the agent.
        external_tool_info (Dict[str, Any]): The external tool outputs.
    """

    thought: str = Field(..., description="The thought process of the agent.")
    action_type: str = Field(
        ..., description="The type of action performed by the agent."
    )
    query: str = Field(..., description="The query requested by the agent.")
    observation: str = Field(..., description="The observation made by the agent.")
    answer: str = Field(..., description="The answer generated by the agent.")
    external_tool_info: Dict[str, Any] = Field(
        ..., description="The external tool outputs."
    )


class LATSGenerateMetrics(BaseModel):
    """LATS generate metrics Pydantic output class.

    Attributes:
        thoughts_metrics (List[PromptInfo]): The metrics of the thoughts.
        actions_metrics (List[PromptInfo]): The metrics of the actions.
        reflections_metrics (List[PromptInfo]): The metrics of the reflections.
    """

    thoughts_metrics: List[PromptInfo] = Field(
        ...,
        description="The metrics of the thoughts.",
    )

    actions_metrics: List[PromptInfo] = Field(
        ...,
        description="The metrics of the actions.",
    )

    reflections_metrics: List[PromptInfo] = Field(
        ...,
        description="The metrics of the reflections.",
    )


class LATSEvaluateMetrics(BaseModel):
    """LATS evaluate metrics Pydantic output class.

    Attributes:
        values_metrics (List[Optional[PromptInfo]]): The metrics of the values.
    """

    values_metrics: List[Optional[PromptInfo]] = Field(
        ...,
        description="The metrics of the values.",
    )


class LATSSimulationStepMetrics(BaseModel):
    """LATS simulation step metrics Pydantic output class.

    Attributes:
        generate_metrics (LATSGenerateMetrics): The metrics of the thoughts, actions, and reflections.
        evaluate_metrics (LATSEvaluateMetrics): The metrics of the values.
    """

    generate_metrics: LATSGenerateMetrics = Field(
        ...,
        description="The metrics of the thoughts, actions, and reflections.",
    )
    evaluate_metrics: LATSEvaluateMetrics = Field(
        ...,
        description="The metrics of the values.",
    )


class LATSSimulationMetrics(BaseModel):
    """LATS simulation metrics Pydantic output class.

    Attributes:
        simulation_step_metrics (List[LATSSimulationStepMetrics]): The metrics of the simulation.
    """

    simulation_step_metrics: List[LATSSimulationStepMetrics] = Field(
        ...,
        description="The metrics of the simulation.",
    )


class LATSSimulationOutput(BaseModel):
    """LATS simulation Pydantic output class.

    Attributes:
        simulation_reward (float): The reward of the simulation from the current node's most valuable child node.
        simulation_terminal_node (Optional[Dict[str, Any]]): The terminal node of the simulation.
        simulation_current_nodes (List[Dict[str, Any]]): The current nodes of the simulation.
        simulation_children_nodes (List[List[Dict[str, Any]]]): The children nodes of the simulation.
        simulation_values (List[List[Dict[str, Any]]]): The values of the children nodes of the simulation.
    """

    simulation_reward: float = Field(
        ...,
        description="The reward of the simulation from the current node's most valuable child node.",
    )
    simulation_terminal_node: Optional[Dict[str, Any]] = Field(
        ...,
        description="The terminal node of the simulation.",
    )
    simulation_current_nodes: List[Dict[str, Any]] = Field(
        ...,
        description="The current nodes of the simulation.",
    )
    simulation_children_nodes: List[List[Dict[str, Any]]] = Field(
        ...,
        description="The children nodes of the simulation.",
    )
    simulation_values: List[List[Dict[str, Any]]] = Field(
        ...,
        description="The values of the children nodes of the simulation.",
    )


class LATSStepOutput(BaseModel):
    """LATS Pydantic output class.

    Attributes:
        iteration (int): The iteration number.
        current_node (Dict[str, Any]): The current node.
        children_nodes (List[Dict[str, Any]]): The children nodes of the current node.
        generate_metrics (LATSGenerateMetrics): The metrics of the thoughts, actions, and reflections.
        values (Optional[List[Dict[str, Any]]]): The values of the children nodes.
        evaluate_metrics (Optional[LATSEvaluateMetrics]): The metrics of the values.
        simulation_results (Optional[LATSSimulationOutput]): The results of the simulation.
        simulation_metrics (Optional[LATSSimulationMetrics]): The metrics of the simulation.
    """

    iteration: int = Field(..., description="The iteration number.")
    current_node: Dict[str, Any] = Field(..., description="The current node.")
    children_nodes: List[Dict[str, Any]] = Field(
        ...,
        description="The children nodes of the current node.",
    )
    generate_metrics: LATSGenerateMetrics = Field(
        ...,
        description="The metrics of the thoughts, actions, and reflections.",
    )
    values: Optional[List[Dict[str, Any]]] = Field(
        ...,
        description="The values of the children nodes.",
    )
    evaluate_metrics: Optional[LATSEvaluateMetrics] = Field(
        ...,
        description="The metrics of the values.",
    )
    simulation_results: Optional[LATSSimulationOutput] = Field(
        ...,
        description="The results of the simulation.",
    )
    simulation_metrics: Optional[LATSSimulationMetrics] = Field(
        ...,
        description="The metrics of the simulation.",
    )


class LATSOutput(BaseOutput):
    """LATS Pydantic output class.

    Attributes:
        additional_info (List[LATSStepOutput]): The additional information of the LATS step output.
    """

    additional_info: List[LATSStepOutput] = Field(
        ...,
        description="The additional information of the LATS step output.",
    )
