_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 55
                - 105
            "2":
                - 49
                - 51
                - 55
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.1
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": darwin-arm64
