site_name: Agential
extra_css:
  - css/extra.css
theme:
  name: material
  logo: _static/assets/bell.svg
  favicon: _static/assets/bell.png
  language: en
  features:
    - header.autohide
    - announce.dismiss
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to night mode
nav:
  - 'index.md'