name: lint
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "discussion_agents/**"
      - "tests/**"
      - ".github/workflows/lint.yml"
  push:
    branches:
      - main
    paths:
      - "discussion_agents/**"
      - "tests/**"
      - ".github/workflows/lint.yml"

env:
  POETRY_VERSION: "1.6.1"
  SUPPORTED_PYTHON_VERSIONS: "3.8 3.9 3.10 3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Install Poetry ${{ env.POETRY_VERSION }}
      run: |
        python -m pip install pipx
        pipx install poetry==${{ env.POETRY_VERSION }}
        poetry --version

    - name: Check Poetry File
      shell: bash
      run: |
        poetry check

    - name: Check lock file
      shell: bash
      run: |
        poetry check --lock

    - name: Install Dependencies
      run: |
        poetry install --with dev

    - name: Run Linter
      run: |
        make lint
