name: test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "discussion_agents/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  push:
    branches:
      - main
    paths:
      - "discussion_agents/**"
      - "tests/**"
      - ".github/workflows/test.yml"

env:
  POETRY_VERSION: "1.6.1"
  SUPPORTED_PYTHON_VERSIONS: "3.9 3.10 3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Install Poetry ${{ env.POETRY_VERSION }}
      run: |
        python -m pip install pipx
        pipx install poetry==${{ env.POETRY_VERSION }}
        poetry --version

    - name: Check Poetry File
      shell: bash
      run: |
        poetry check

    - name: Check lock file
      shell: bash
      run: |
        poetry check --lock

    - name: Install Dependencies
      run: |
        poetry install --with dev

    - name: Run Test (No Cost)
      run: |
        export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
        export HUGGINGFACEHUB_API_TOKEN="${{ secrets.HUGGINGFACEHUB_API_TOKEN }}"
        make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: false
        verbose: true
